# Generated by Django 5.2.1 on 2025-12-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='participant',
        ),
        migrations.AddField(
            model_name='bet',
            name='participant',
            field=models.ManyToManyField(related_name='bets', to='participants.participant'),
        ),
    ]
