# Generated by Django 5.2.1 on 2025-12-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_remove_bet_participant_bet_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='participant',
            new_name='participants',
        ),
    ]
