# Generated by Django 5.2.1 on 2025-12-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_rename_participant_bet_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedpot',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='unorderedpot',
            name='total_amount',
        ),
    ]
